Change `// test_output! output` to `//! test_output(output)`
voltrevo/ValueScript pull request #11
Opened 2023-03-21 15:15 UTC by tarunsamanta2k20

#7

2023-03-22 22:03 UTC, voltrevo commented
Great to see a start here @tarunsamanta2k20.

I've marked the PR as a draft as the changes are incomplete. Let me know if you need any help completing #7.

2023-03-23 13:05 UTC, SamantaTarun commented
Please let me know, if any, changes require.

2023-03-23 23:29 UTC, voltrevo requested changes
Heya. Thanks for the update, more changes are needed though.

In addition to my comment:
- the `)` of the annotation needs to be handled
- all the files with `// test_output! ...` need to be changed, not just `anonymousMain.ts`

Use `cargo test` locally to check your changes. Also sample a few of the annotations and check that they are actually being tested by (temporarily) adjusting the annotation to ensure the test breaks when it asserts the wrong output.

If you have discord it might be better to discuss in more detail over there. I'm voltrevo#6526.

2023-03-23 23:29 UTC, voltrevo commented on vstc/src/test_inputs.rs
> +        if first_line.starts_with("//! test_output ") {
This won't match the new format, the start of the pattern is `"//! test_output("`.

2023-03-23 23:47 UTC, voltrevo commented on vstc/src/test_inputs.rs
> +        if first_line.starts_with("//! test_output ") {
Optional: I'd also suggest that we filter on `//!`, and then if the pattern isn't recognized, we fail the file for that too.

2023-03-23 23:48 UTC, tarunsamanta2k20 commented
@voltrevo let me give a try.

2023-04-02 15:22 UTC, tarunsamanta2k20 commented
@voltrevo please let me know clearly what needed to be done?

2023-04-03 01:04 UTC, voltrevo commented
@tarunsamanta2k20 The following is still needed:

1. All files containing `test_output!` need to be updated (about 100 files), not just the one you changed
2. It needs to work correctly. `if first_line.starts_with("// test_output! ")` is wrong - it results in no tests being found.

I can see that `cargo test` technically passes on your branch, but this is because none of the tests are being found. Use `cargo test -p vstc -- --nocapture` to get a more verbose output. This is the output from the main branch:

<details>
<summary>Click to expand</summary>

```
➜  ValueScript git:(main) cargo test -p vstc -- --nocapture
   Compiling valuescript_common v0.1.0 (/Users/andrew/workspaces/ValueScript/valuescript_common)
   Compiling valuescript_compiler v0.1.0 (/Users/andrew/workspaces/ValueScript/valuescript_compiler)
   Compiling valuescript_vm v0.1.0 (/Users/andrew/workspaces/ValueScript/valuescript_vm)
   Compiling vstc v0.1.0 (/Users/andrew/workspaces/ValueScript/vstc)
    Finished test [unoptimized + debuginfo] target(s) in 5.08s
     Running unittests src/main.rs (target/debug/deps/vstc-1458690d5106a7a4)

running 1 test

Testing /Users/andrew/workspaces/ValueScript/inputs/failing/numberMethods/toExponentialInconsistent.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/failing/stringIteration.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/anonymousMain.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/arrayBuiltin.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/assignmentEvalOrder.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/assignmentEvalOrder2.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/bigint/noMix.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/binaryTree.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/boolean.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/capture.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/captureButNotRefBeforeInit.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/captureShadowed.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/complexPatternOrder.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/counter.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/destructuring/decl/array.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/destructuring/decl/multi_complex.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/destructuring/decl/object.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/destructuring/param/array.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/destructuring/param/multi_complex.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/destructuring/param/object.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/dontRevertMath.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/doublePreInc.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/exceptions/catchDestructure.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/exceptions/finallyBreakSwallowsException.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/exceptions/finallyBreakSwallowsReturn.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/exceptions/finallyReturnSwallowsException.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/exceptions/finallyWithoutThrow.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/exceptions/isReturningReset.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/exceptions/nestedFinallyReturn.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/exceptions/nestedTry.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/exceptions/revertMethodCallOnCatch.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/exceptions/revertOnCatch.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/exceptions/revertSmallQueue.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/exceptions/tryCatch.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/exceptions/tryCatchFinally.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/exceptions/tryFinally.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/exceptions/tryReturnFinallyReturn.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/forOf.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/hello.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/importBar.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/importFoo.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/importFooAndBar.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/importFoobar.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/mergeSort.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/multiAssignment.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/multiCompoundAssignment.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/mutatedRegisterIssue.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/nestedAssignment.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/nestedCompoundAssignment.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/nestedFn.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/nestedFnCapture.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/numberMethods/isInteger.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/numberMethods/isSafeInteger.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/numberMethods/parseFloat.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/numberMethods/parseInt.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/numberMethods/toExponential.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/numberMethods/toFixed.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/patternEvalOrder.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/patternEvalOrder2.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/preincrement.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/projEuler/p1.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/projEuler/p11.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/projEuler/p13.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/projEuler/p15.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/projEuler/p16.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/projEuler/p18.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/projEuler/p19.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/projEuler/p2.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/projEuler/p25.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/projEuler/p3.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/projEuler/p4.ts ...

Testing /Users/andrew/workspaces/ValueScript/inputs/passing/projEuler/p5.ts ...
Debug.log: { factors: [ 2, 2, 3 ] }
Debug.log: { factors: [ 2, 2, 3, 5 ] }
Debug.log: { factors: [ 2, 2, 2, 3, 5, 7 ] }
Debug.log: { factors: [ 2, 2, 2, 3, 3, 5, 7 ] }
Debug.log: { factors: [ 2, 2, 2, 3, 3, 5, 7 ] }
Debug.log: { factors: [ 2, 2, 2, 3, 3, 5, 7, 11 ] }
Debug.log: { factors: [ 2, 2, 2, 3, 3, 5, 7, 11, 13 ] }
Debug.log: { factors: [ 2, 2, 2, 3, 3, 5, 7, 11, 13 ] }
Debug.log: { factors: [ 2, 2, 2, 2, 3, 3, 5, 7, 11, 13 ] }
Debug.log: { factors: [ 2, 2, 2, 2, 3, 3, 5, 7, 11, 13, 17 ] }
Debug.log: { factors:  [...]

2023-05-24 03:04 UTC, voltrevo commented
Hi @tarunsamanta2k20, it looks like your last commit might be a mistake. Maybe you meant to commit something else? It's just added the compiled javascript files. My previous comment reviewing your changes still stands.

The compiled javascript files are also an additional problem. I'll need you to undo this commit before proceeding:

```sh
# Create a backup of your current branch
git checkout -b backup

# Switch back to your branch
git checkout -

# Undo the last commit, this is the same as "Git: Undo Last Commit" in vs code
git reset --soft HEAD^1

# You should now see the js files as staged uncommitted changes

# Unstage and delete those js files
git reset # unstage
git checkout . # delete

# Overwrite the remote, using -f to allow removing history
git push -f
```

If you want to run `tsc` to check the types, use `tsc --noEmit`. This will give you all the type checking without generating the js files.

In future, please check the diff of your PR to make sure the changes there are intended before asking for a review.

2023-05-26 02:58 UTC, voltrevo commented
@tarunsamanta2k20 Hmm I'm going to want this change sooner or later and I'm afraid I'm going to end up dropping this and doing it myself.

How about a different approach - add me as a collaborator on your fork, that way I can push to your branch and we can work on this together.

Rather than fix up this branch, I'd have us start over. There's new test files that need to be included anyway.

I suggest you just make a new branch from latest main do the literal `// test_output! output` to `//! test_output(output)` in all the test files. Then I'll take care of updating `test_inputs.rs`, and we can get it merged in.

Wdyt?

2023-05-26 22:57 UTC, tarunsamanta2k20 commented
@voltrevo I have added you as a collaborator to my  fork. Let me know if anything required from my side.

2023-05-27 00:48 UTC, voltrevo commented
@tarunsamanta2k20 Great. Here's what I want you to do now:

1. Reset your branch and pull in the latest changes
2. Update *all* the files in `inputs` to use the new `//! test_ouput(output)` pattern
3. Commit and push
4. Double check the PR has the correct changes
5. Let me know and I'll take care of the rest :)

2023-05-27 10:53 UTC, tarunsamanta2k20 commented
@voltrevo inside (output) should I put the output which is just next to it?

2023-05-27 10:54 UTC, tarunsamanta2k20 commented
Like // ! test_ouput(42)

2023-05-29 08:49 UTC, voltrevo commented
> @tarunsamanta2k20 Like // ! test_ouput(1) or it should be like that?
> 
> //! test_ouput(output) 1 // (Should be 0.)

First one 👍

2023-05-29 14:29 UTC, tarunsamanta2k20 commented
@voltrevo i am getting 75 results in main branch. have you modified anything?

![image](https://github.com/voltrevo/ValueScript/assets/55488549/7381e134-4460-4dea-9ea7-34861965ad5f)

2023-05-30 08:41 UTC, tarunsamanta2k20 commented
@voltrevo give me some time, will make all those changes.

2023-05-30 10:20 UTC, tarunsamanta2k20 commented
@voltrevo these three files are not present in your main branch. that's why i couldn't resolve merge conflicts.

 inputs/failing/assignmentEvalOrder.ts
inputs/failing/doublePreInc.ts
inputs/failing/stringIteration.ts

2023-05-31 02:07 UTC, voltrevo commented
Awesome.

> that's why i couldn't resolve merge conflicts

All good. I'll fix it up and take it from here :).

2023-05-31 02:30 UTC, voltrevo approved these changes

2023-05-31 02:32 UTC, voltrevo commented
Looks like there's an issue with the gh action when running against PRs. I'll look into fixing that up next time. It's not a true failure of this change.

2023-05-31 02:32 UTC, merged

2023-05-31 02:33 UTC, voltrevo commented
@tarunsamanta2k20 Congrats on being the first outside contributor to ValueScript 🥳.